In [1]:
import pandas as pd

In [2]:
ser = pd.Series([10,20,30,40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
df = pd.DataFrame([[10, "a", True],
                  [20, "b", False],
                  [30, "c", False],
                  [40, "d", True]])
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [3]:
import numpy as np
df = pd.DataFrame(np.arange(100).reshape((25,4)))

In [8]:
df.head()

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [9]:
df.tail()

     0   1   2   3
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [10]:
df.shape

(25, 4)

In [11]:
df = pd.DataFrame(np.arange(6).reshape((3,2)))
df

   0  1
0  0  1
1  2  3
2  4  5

In [12]:
df.index = ["01","02","03"]
df.columns = ["A", "B"]
df

    A  B
01  0  1
02  2  3
03  4  5

In [4]:
named_df = pd.DataFrame(np.arange(6).reshape((3,2)),
                       columns=["A列","B列"],
                       index=["1行目","2行目","3行目"])
named_df

     A列  B列
1行目   0   1
2行目   2   3
3行目   4   5

In [5]:
pd.DataFrame({"A列":[0, 2, 4], "B列":[1, 3, 5]})

   A列  B列
0   0   1
1   2   3
2   4   5

In [4]:
import pandas as pd
import numpy as np

In [5]:
named_df=pd.DataFrame(np.arange(6).reshape((3,2)),
                      columns=["A列","B列"],
                      index=["1行目","2行目","3行目"])
named_df

     A列  B列
1行目   0   1
2行目   2   3
3行目   4   5

In [6]:
pd.DataFrame({"A列":[0,2,4],"B列":[1,3,5]})

   A列  B列
0   0   1
1   2   3
2   4   5

In [7]:
df=pd.DataFrame(np.arange(12).reshape((4,3)),
                columns=["A","B","C"],
                index=["1行目","2行目","3行目","4行目"])
df

     A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [8]:
df["A"]

1行目    0
2行目    3
3行目    6
4行目    9
Name: A, dtype: int64

In [10]:
df[["A", "B"]]

     A   B
1行目  0   1
2行目  3   4
3行目  6   7
4行目  9  10

In [23]:
df.loc[:,:]

     A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [25]:
df.loc[["1行目","3行目"],:]

     A  B  C
1行目  0  1  2
3行目  6  7  8

In [26]:
df.loc[["1行目"],["A","C"]]

     A  C
1行目  0  2

In [27]:
df.iloc[1, 1]

4

In [28]:
df.iloc[1:,1]

2行目     4
3行目     7
4行目    10
Name: B, dtype: int64

In [29]:
df.iloc[1:, :2]

     A   B
2行目  3   4
3行目  6   7
4行目  9  10